Личный проект: накорми слона
htmlacademy-nodejs/42634-typoteka-3 pull request #14
Opened 2021-12-08 11:14 UTC by KuryakovDen

2021-12-09 05:28 UTC, what1s1ove requested changes

2021-12-09 05:28 UTC, what1s1ove commented on src/fill-db.sql
> +insert into articles (title, createdDate, image, announce, fullText, user_id) values
у тебя что-то в кебабе. а что-то в снейк кейсе. должно быть все единообразно

2021-12-09 05:28 UTC, what1s1ove commented on src/fill-db.sql
> +insert into comments (article_id, user_id, createdDate, text) values
тут то же

2021-12-09 05:57 UTC, KuryakovDen commented on src/fill-db.sql
> +insert into articles (title, createdDate, image, announce, fullText, user_id) values
Поправил, сделал все поля таблицы в camelCase

2021-12-09 05:57 UTC, KuryakovDen commented on src/fill-db.sql
> +insert into comments (article_id, user_id, createdDate, text) values
Поправил, сделал все поля таблицы в camelCase

2021-12-09 09:25 UTC, what1s1ove requested changes
Должно быть все по схеме

https://github.com/htmlacademy-nodejs/42634-typoteka-3/blob/b7fa295a727c8f3deac1fcd9ed717a14e63d76eb/src/schema.sql

У тебя сейчас другая схема (название ключей и тд)

Ты проверяешь то что пишешь? 🤔

2021-12-11 14:39 UTC, what1s1ove approved these changes

2021-12-11 14:39 UTC, merged