Личный проект: вспомнить всё
htmlacademy-nodejs/42634-typoteka-3 pull request #16
Opened 2021-12-17 14:13 UTC by KuryakovDen

2021-12-17 16:52 UTC, what1s1ove requested changes

2021-12-17 16:52 UTC, what1s1ove commented on package.json
> +    "sequelize": "6.12.0-beta.3"
с этим осторожно нужно быть
установи версию как в учебном проекте

2021-12-17 16:52 UTC, what1s1ove commented on src/service/cli/server.js
> +      process.exit(1);
добавь енам на статус выхода

2021-12-18 07:04 UTC, KuryakovDen commented on src/service/cli/server.js
> +      process.exit(1);
Добавил enum

2021-12-18 07:05 UTC, KuryakovDen commented on package.json
> +    "sequelize": "6.12.0-beta.3"
Поставил версию пакета 6.3.5

2021-12-18 12:00 UTC, what1s1ove approved these changes

2021-12-18 12:00 UTC, merged